name: SofaData Daily Sync

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Increased slightly for safe batching
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests curl_cffi pycountry

      - name: Run Scraper
        run: python fetch_data.py

      - name: Commit Data
        run: |
          git config --global user.name "CricFoot-Bot"
          git config --global user.email "bot@cricfoot.net"
          git add data/
          git commit -m "Sync: H2H, Lineups, Stats, Odds, Form" || exit 0
          git push
